### ISSUE TITLE
Add an option for user's picture instead of yellow default picture.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#2]

**Comment by shreyanshdwivedi** [comment]
@Anupam-dagar u can try cloudinary to store pic uploaded by user..

**Comment by namantw** [comment]
I want to try this @Anupam-dagar

**Comment by Anupam-dagar** [comment]
@namantw assigned

**Comment by namantw** [comment]
@Anupam-dagar I have more than two issues assigned right now, please unassign me from this

**Comment by Tlazypanda** [comment]
I want to try this .

**Comment by Anupam-dagar** [comment]
@Tlazypanda assigned
