### ISSUE TITLE
Enter date of birth via pop up calander

### ISSUE THREAD

**Issue by gauthamzz** [Anupam-dagar/Portfolio-Generator#20]
Now an individual needs to type in the date in the format to enter it.

**Comment by saifat29** [comment]
@gauthamzz I want to do it.

**Comment by Anupam-dagar** [comment]
@saifat29 it's all yours

**Comment by saifat29** [comment]
@Anupam-dagar I'll submit PR as soon as possible.

**Comment by saifat29** [comment]
@gauthamzz @Anupam-dagar Can you suggest some popup calendar widgets, I'm new to Django so I don't have a good idea which should I use.
