### ISSUE TITLE
New portfolio template

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#22]
Create a frontend for portfolio template so that the user has option to chose from one of the two templates.

**Comment by dojutsu-user** [comment]
can we use a free template?

**Comment by Anupam-dagar** [comment]
yeah you are free to use anything but it should be suitable for a portfolio.I would recommend commenting link of template here before you start working.

**Comment by Panda2498** [comment]
Can I go ahead with this issue?

**Comment by gauthamzz** [comment]
Okay

**Comment by Anupam-dagar** [comment]
P.S this issue is not for a single person, multiple people can work on this.

**Comment by Panda2498** [comment]
Okay

**Comment by gauthamzz** [comment]
it would be nice,if there is as easy way to add templates. like user can upload template or something like that. Dont have much idea. will think and say in few days.

**Comment by Anupam-dagar** [comment]
@gauthamzz i think it will be difficult to implement,Many factors will be there.
