### ISSUE TITLE
new home page

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#28]
it will be good if the home page can be converted to a minimal one.

**Comment by hacker1x1x1** [comment]
sir, can you just elaborate more on this issue!

**Comment by gauthamzz** [comment]
first rule,dont call sir on github

**Comment by hacker1x1x1** [comment]
okay

**Comment by hacker1x1x1** [comment]
i would like to work on this

**Comment by Anupam-dagar** [comment]
@hacker1x1x1 assigned to you

**Comment by Anupam-dagar** [comment]
@hacker1x1x1 update on this?

**Comment by hacker1x1x1** [comment]
i am creating a whole new homepage with css
is that fine?
