### ISSUE TITLE
implement github api

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#30]

**Comment by aniketgattani** [comment]
@Anupam-dagar i want to work on this issue. Correct me if i am wrong u want the github api integrated in the side panel right ?

**Comment by Anupam-dagar** [comment]
@aniketgattani yeah sure
yup implement oauth, leave space for apikey and secret, I'll add my credentials there.
Implement it as same as google and fb are there.
The one i used already has github definitions in it, it will make it easy to implement.
Take help from here
https://simpleisbetterthancomplex.com/tutorial/2016/10/24/how-to-add-social-login-to-django.html

**Comment by aniketgattani** [comment]
@Anupam-dagar unfortunately share-this doesnt have a github api. Hence we will have to make a custom UI for the sharing buttons :\

**Comment by Anupam-dagar** [comment]
there is a misunderstanding, you need to add a button in login and signup area
share-this is for sharing and we can't share on github

**Comment by AK-007** [comment]
I would like to work on it.

**Comment by Anupam-dagar** [comment]
@AK-007 assigned

**Comment by AK-007** [comment]
@Anupam-dagar How can I view the website after setting up virtual environment?

**Comment by AK-007** [comment]
I am getting this after setting up the virtual environment
![screenshot 62](https://user-images.githubusercontent.com/26346816/34915144-ae27eaf2-f946-11e7-9a10-3cc0dd812bca.png)

**Comment by hacker1x1x1** [comment]
yeah, i too has the same problem in setting up the project
@Anupam-dagar

**Comment by Anupam-dagar** [comment]
issue tracker is not a good place to ask this, message on zulip streams.As written in documentation, you need to generate a secret key online and place it in settings.
