### ISSUE TITLE
Error regarding required fields in the form

### ISSUE THREAD

**Issue by Jigar3** [Anupam-dagar/Portfolio-Generator#34]
In the forms not all required fields raise an error during blank values.
Like although name, email, contact are required one can skip these steps to directly Submit the form, although the portfolio isn't created after submitting it justs redirects to the first form.

**Comment by Anupam-dagar** [comment]
you need to click on them once to display the error, you can go on fixing it.

**Comment by abhishhh1** [comment]
I would like to work on this issue

**Comment by Anupam-dagar** [comment]
@abhishhh1 assigned
