### ISSUE TITLE
Efficient way to get details from the user.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#4]
Currently, a user has to go through filling 7 steps form to get portfolio generated.This needs to be reduced.Suggestions are welcome for the same.

**Comment by gauthamzz** [comment]
I think we need to first use the OAuth values to the form. Should make an issue for that first

**Comment by gauthamzz** [comment]
Add an issue to get name of user etc from Oaut, telling user to type it everytime is not nice.

**Comment by ProBeta1** [comment]
Using Voice-input.
Both Chrome and Firefox have this extension.

**Comment by ProBeta1** [comment]
OR (Inclusive):)
We can make an interactive chatbot , which asks the details of the user , instead of showing up the form-format.
