### ISSUE TITLE
receive user details from oauth and fill them automatically in the details form

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#40]

**Comment by Jigar3** [comment]
I would like to this

**Comment by Anupam-dagar** [comment]
@Jigar3 assigned

**Comment by Jigar3** [comment]
Any resources you might know of that would help me solving this issue

**Comment by gauthamzz** [comment]
Do you know django, did you set up this project locally yet?

**Comment by Anupam-dagar** [comment]
fb and google oauth is already implemented, currently get details from that only, it has some data in it.
how the oauth was implemented can be seen here
https://simpleisbetterthancomplex.com/tutorial/2016/10/24/how-to-add-social-login-to-django.html

**Comment by Jigar3** [comment]
@gauthamzz 
I kind of know django and I have setup this project locally as well

**Comment by Jigar3** [comment]
https://axiacore.com/blog/how-retrieve-facebook-extra-info-from-django/
I found this regarding accessing facebook info from the user.
I want to know what all info should I access.
Here is a list of all permissions:
https://developers.facebook.com/docs/facebook-login/permissions/
@Anupam-dagar @gauthamzz

**Comment by Anupam-dagar** [comment]
we need users name, email, profile link, any other social media links if he has added to his account, phone number, fb dp.date of birth, bio field.except projects and skills all other details maybe present on fb.Try for all these details.If user has not set some field then it will return null

**Comment by Anupam-dagar** [comment]
okay, take your time
