### ISSUE TITLE
Invalid repo-language detection by Github linguist library.

### ISSUE THREAD

**Issue by jamesgeorge007** [Anupam-dagar/Portfolio-Generator#43]
@Anupam-dagar 

As you can see the repo language is auto-detected to be CSS since it is the major part of the code.
Well you can make it to Python by adding a .gitattributes file .

Add the following content to it:

*.css linguist-language=Python

**Comment by Anupam-dagar** [comment]
thanx @jamesgeorge007 for the help :smile:. I would be happy to merge your PR for the same. Let me know or else I'll commit self if you don't want to :smile:

**Comment by jamesgeorge007** [comment]
I had created a pull request as you asked me with the changes required. :smiley: :
