### ISSUE TITLE
Aadhaar verification

### ISSUE THREAD

**Issue by pradeepgangwar** [Anupam-dagar/Portfolio-Generator#45]
@Anupam-dagar With respect to recent developments by modi govt. to digitize various services and link them with aadhaar. I would like to request you to please allow Aadhaar verification with HoxNox. Else It will become very difficult for users to get job without aadhaar verified portfolios.

**Comment by Anupam-dagar** [comment]
@pradeepgangwar would you like to work on iy? I will be glad to merge the PR. :p

**Comment by pradeepgangwar** [comment]
@Anupam-dagar Currently I am a little busy. Will take a look as soon as possible. :hammer:
