### ISSUE TITLE
Fix typo.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#6]
There are some typo's and grammatical error here and there on the website that needs to be fixed.

**Comment by pulkonet** [comment]
@Anupam-dagar Shall I do this?

**Comment by Anupam-dagar** [comment]
@pulkonet yeah sure

**Comment by pulkonet** [comment]
@Anupam-dagar I claimed this issue but someone else fixed it. Please mark it as closed and from the next time onwards please assign the issues so that other people get to know that someone is working on this.

**Comment by Anupam-dagar** [comment]
that PR was for readme.md, there are some typo's and grammatical error in the website itself, you can check them.

**Comment by pulkonet** [comment]
Okay I'll check them.

**Comment by kira0204** [comment]
Let's close this?

**Comment by pulkonet** [comment]
Sure.
