### ISSUE TITLE
Create 404 error page.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#7]
Currently, the website doesn't have any 404 error page and just shows default 404 white page error.

**Comment by komcal** [comment]
@Anupam-dagar I can help with this.

**Comment by Anupam-dagar** [comment]
@komcal yeah sure.

**Comment by kunalvishnoi** [comment]
@Anupam-dagar  may i go for this?

**Comment by Anupam-dagar** [comment]
@kunalvishnoi yeah go ahead. komcal hasn't created any PR from last 3 days.

**Comment by kunalvishnoi** [comment]
![screenshot 97](https://user-images.githubusercontent.com/24695316/31054194-195bf3aa-a6cb-11e7-9907-fbbd46e6d9f4.png)
this page works?

**Comment by Divy123** [comment]
Can I go with it?

**Comment by Divy123** [comment]
@Anupam-dagar sir Can I go with it?

**Comment by Anupam-dagar** [comment]
@Divy123 yeah sure.
P.S you don't have to call anybody sir on GitHub :smile:
