### ISSUE TITLE
Automatically fill Oauth values to enter details form.

### ISSUE THREAD

**Issue by Anupam-dagar** [Anupam-dagar/Portfolio-Generator#9]
Name and other details obtained from Oauth are not used in the form, the user has to enter it again.Prefill the field in the form whose details are obtained from Oauth.

**Comment by gauthamzz** [comment]
Adding the feature to extract your projects from GitHub is also a great feature.

Also trying to generate a profile automatically from linked in would be also amazing.( Need to read about this a bit)

**Comment by kira0204** [comment]
Setting up Django, it throws 500 error code. Any advice else I will start digging

**Comment by Anupam-dagar** [comment]
generate a secret key and put in settings.py
also change debug = true.
If it doesn't works then it will show you the error, post the screenshot here if error persist

**Comment by gauthamzz** [comment]
break this down to smaller multiple issues issues @Anupam-dagar

**Comment by Anupam-dagar** [comment]
cool
